### ISSUE TITLE
1.1-spark3 jar in sonatype

### ISSUE THREAD

**Issue by AlonsoGuevara** [criteo/Spark-RSVD#10]
Folks,

Now that 1.1-spark3 has been marked for release, will the jar be published to https://repository.sonatype.org/ ?

Thanks!

**Comment by alois-bissuel** [comment]
Hello,

We are trying to publish the jars in sonatype, but so far there are some problems during the publishing phase. We will keep you informed on the progress we are making.

**Comment by AlonsoGuevara** [comment]
Just saw you even uploaded the fat jar! Thanks a lot :)
I'll close this
