### ISSUE TITLE
similar library for PySpark

### ISSUE THREAD

**Issue by alesspalma** [criteo/Spark-RSVD#7]
Is there any similar implementation for Spark on Python, namely PySpark?

**Comment by alois-bissuel** [comment]
Hello @alesspalma ,
We don't have a similar implementation for PySpark, though we use this library internally using PySpark. We will try to add some bindings on the JVM side for an easier usage with PySpark.

**Comment by alesspalma** [comment]
great!

**Comment by alois-bissuel** [comment]
Bindings are added in v1.1!
