### ISSUE TITLE
BlockMatrix as input in Pyspark ?

### ISSUE THREAD

**Issue by yijui** [criteo/Spark-RSVD#9]
I already have a BlockMatrix in Pyspark, how can I directly use it as input to Spark-RSVD and return singular vectors of the type BlockMatrix ?

**Comment by alois-bissuel** [comment]
You will find some relevant examples in the [code](../blob/master/python/example.py) now!

**Comment by yijui** [comment]
Thank you, @alois-bissuel.
I will try this library in my research !
